# -*- coding: utf-8 -*-
"""ARCHER + ASSASSIN + SUPPORT skill data"""
from _skill_data import make_row

# ══════════════════════════════════════════════════════════════
# ARCHER SKILLS (20 units)
# ══════════════════════════════════════════════════════════════

ARCHER = [
    # T1
    make_row(id='rock_throw_stun', name='Ném Đá',
        descriptionVi="Khỉ Lao Cành ném đá mạnh vào mục tiêu, gây sát thương vật lý (20 + 0.8x ATK) và có 30% tỷ lệ choáng 1 lượt. Xạ thủ bậc thấp kèm khống chế. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='rock_throw_stun', damageType='physical', base='20', scaleStat='atk', scale='0.8', stunChance='0.30', stunTurns='1'),
    make_row(id='multi_sting_poison', name='Châm Liên Hoàn',
        descriptionVi="Ong Bắp Cày bắn 2 mũi kim vào mục tiêu, gây sát thương vật lý (16 + 0.65x ATK) mỗi mũi kèm độc nhẹ 8 sát thương/lượt trong 2 lượt. Xạ thủ đa đòn + DOT. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='multi_sting_poison', damageType='physical', base='16', scaleStat='atk', scale='0.65', maxHits='2', poisonTurns='2', poisonPerTurn='8'),
    make_row(id='heat_seek', name='Tầm Nhiệt',
        descriptionVi="Diều Hâu Săn tự tìm kẻ HP thấp nhất trên chiến trường để tấn công, gây sát thương vật lý (18 + 0.7x ATK), x2 sát thương nếu mục tiêu dưới 50% HP. Xạ thủ kết liễu. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='heat_seek', damageType='physical', base='18', scaleStat='atk', scale='0.7'),
    make_row(id='piercing_shot', name='Lao Xuyên',
        descriptionVi="Chim Sẻ Lao bắn mũi tên xuyên nguyên hàng ngang, gây sát thương vật lý (18 + 0.75x ATK) giảm 20% mỗi mục tiêu sau. Xạ thủ xuyên hàng bậc thấp. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='piercing_shot', damageType='physical', base='18', scaleStat='atk', scale='0.75'),
    # T2
    make_row(id='arrow_rain', name='Mưa Tên',
        descriptionVi="Đại Bàng Xạ Thủ bắn 3 mũi tên ngẫu nhiên vào các kẻ địch, mỗi mũi gây sát thương vật lý (18 + 0.7x ATK). Xạ thủ đa mục tiêu ngẫu nhiên. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='arrow_rain', damageType='physical', base='18', scaleStat='atk', scale='0.7', maxHits='3'),
    make_row(id='snipe_execute', name='Mỏ Xuyên',
        descriptionVi="Chim Mỏ To ngắm bắn chính xác vào điểm yếu mục tiêu, gây sát thương vật lý (22 + 0.85x ATK), x2 sát thương nếu mục tiêu dưới 30% HP. Xạ thủ kết liễu cấp 2. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='snipe_execute', damageType='physical', base='22', scaleStat='atk', scale='0.85'),
    make_row(id='beak_disarm', name='Mỏ Kẹp',
        descriptionVi="Diệc Xuyên dùng mỏ dài kẹp chặt vũ khí mục tiêu, gây sát thương vật lý (22 + 0.8x ATK) và tước vũ khí 1 lượt (giảm ATK 30%). Xạ thủ debuff hiệu quả. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='beak_disarm', damageType='physical', base='22', scaleStat='atk', scale='0.8'),
    make_row(id='rapid_fire', name='Khoan Liên Tục',
        descriptionVi="Chim Gõ Kiến bắn 3 phát liên tục vào cùng mục tiêu, mỗi phát gây sát thương vật lý (10 + 0.45x ATK). Tổng 3 phát tạo burst damage tập trung. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='rapid_fire', damageType='physical', base='10', scaleStat='atk', scale='0.45'),
    # T3
    make_row(id='unit_skill_owl_nightshot', name='Mũi Tên Ngủ',
        descriptionVi="Cú Đêm bắn mũi tên tẩm thuốc mê vào mục tiêu, gây sát thương vật lý (28 + 1.0x ATK). Chọn ngẫu nhiên kẻ địch nộ cao nhất để ru ngủ: 1★ ru 1, 2★ ru 2, 3★ ru 3 mục tiêu. Tỷ lệ 30% mỗi mục tiêu. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='single_sleep', damageType='physical', base='28', scaleStat='atk', scale='1.0', sleepChance='0.30', sleepTurns='1'),
    make_row(id='fish_bomb_aoe', name='Bom Cá',
        descriptionVi="Bồ Nông Bom thả bom cá nổ tại 9 ô vuông quanh mục tiêu, gây sát thương vật lý (25 + 0.9x ATK) và 25% choáng 1 lượt. Xạ thủ vùng rộng + CC. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='fish_bomb_aoe', damageType='physical', base='25', scaleStat='atk', scale='0.9', stunChance='0.25', stunTurns='1'),
    make_row(id='sniper_crit', name='Phát Bắn Tỉa',
        descriptionVi="Chim Cánh Cụt Bắn ngắm bắn tỉa chính xác vào mục tiêu, gây sát thương vật lý (30 + 1.05x ATK) và bỏ qua 40% giáp. Xạ thủ đơn mục tiêu sát thương cao. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='sniper_crit', damageType='physical', base='30', scaleStat='atk', scale='1.05', armorPen='0.40'),
    make_row(id='fire_arrow_burn', name='Tên Lửa Hồng',
        descriptionVi="Hồng Hạc Bắn bắn mũi tên lửa vào mục tiêu, gây sát thương vật lý (28 + 0.95x ATK) và đốt cháy 12 sát thương/lượt trong 2 lượt. Xạ thủ + DOT lửa. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='fire_arrow_burn', damageType='physical', base='28', scaleStat='atk', scale='0.95', poisonTurns='2', poisonPerTurn='12'),
    # T4
    make_row(id='unit_skill_cat_goldbow', name='Phá Giáp Tiễn',
        descriptionVi="Ong Lửa bắn mũi tên phá giáp vào mục tiêu, gây sát thương vật lý (32 + 1.1x ATK) và giảm 12 giáp trong 2 lượt. Setup phá giáp cho đồng đội dồn sát thương. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='single_armor_break', damageType='physical', base='32', scaleStat='atk', scale='1.1', armorBreak='12', turns='2'),
    make_row(id='dark_feather_debuff', name='Bão Lông Vũ Đen',
        descriptionVi="Quạ Bão Táp phóng lông vũ sắc nhọn vào 3 mục tiêu ngẫu nhiên, gây sát thương vật lý (28 + 0.9x ATK) mỗi mục tiêu và giảm ATK 15% trong 2 lượt. Xạ thủ debuff đa mục tiêu. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='dark_feather_debuff', damageType='physical', base='28', scaleStat='atk', scale='0.9', maxHits='3', turns='2'),
    make_row(id='dive_bomb', name='Bổ Nhào',
        descriptionVi="Chim Trời Mây bổ nhào từ trên cao xuống nguyên cột, gây sát thương vật lý (30 + 1.0x ATK) và phá 12 giáp trong 2 lượt. Xạ thủ tấn công cột + phá giáp. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='dive_bomb', damageType='physical', base='30', scaleStat='atk', scale='1.0', armorBreak='12', turns='2'),
    make_row(id='feather_bleed', name='Lông Vũ Cắt',
        descriptionVi="Hải Âu Gió bắn 3 lông vũ sắc như dao vào mục tiêu ngẫu nhiên, gây sát thương vật lý (25 + 0.85x ATK) mỗi mục tiêu kèm chảy máu 10 sát thương/lượt trong 2 lượt. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='feather_bleed', damageType='physical', base='25', scaleStat='atk', scale='0.85', maxHits='3', turns='2'),
    # T5
    make_row(id='unit_skill_phoenix_arrow', name='Tên Lửa Phượng Hoàng',
        descriptionVi="Phượng Hoàng Tên phóng mũi tên lửa nổ hình thập (+) vào mục tiêu, gây sát thương vật lý (38 + 1.2x ATK) lên mục tiêu chính và 4 ô liền kề. Xạ thủ vùng thập T5. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='cross_5', damageType='physical', base='38', scaleStat='atk', scale='1.2'),
    make_row(id='unit_skill_garuda_divine', name='Tên Thần Garuda',
        descriptionVi="Garuda Thần phóng kim độc thần thánh vào mục tiêu ngẫu nhiên: 1★ bắn 2, 2★ bắn 3, 3★ bắn 4 mục tiêu. Mỗi kim gây sát thương vật lý (36 + 1.3x ATK) đầy đủ. Xạ thủ đa mục tiêu T5. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='random_multi', damageType='physical', base='36', scaleStat='atk', scale='1.3', maxHits='2'),
    make_row(id='unit_skill_thunderbird_storm', name='Mũi Tên Sấm Sét',
        descriptionVi="Chim Sấm Sét bắn mũi tên sét xuyên qua nhiều mục tiêu cùng hàng, gây sát thương vật lý (35 + 1.15x ATK) cho tối đa 4 mục tiêu. Xạ thủ xuyên hàng T5. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='row_multi', damageType='physical', base='35', scaleStat='atk', scale='1.15', maxHits='4'),
    make_row(id='unit_skill_roc_legend', name='Lông Vũ Bão Táp',
        descriptionVi="Tổ Chim Huyền Thoại phóng hàng loạt lông vũ sắc nhọn vào 3 ô trước mặt theo dải tam giác, gây sát thương vật lý (40 + 1.25x ATK). Xạ thủ vùng nón T5. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='cone_shot', damageType='physical', base='40', scaleStat='atk', scale='1.25'),
]

# ══════════════════════════════════════════════════════════════
# ASSASSIN SKILLS (20 units)
# ══════════════════════════════════════════════════════════════

ASSASSIN = [
    # T1
    make_row(id='flame_combo_assassin', name='Lửa Cáo',
        descriptionVi="Cáo Hỏa lao sau lưng mục tiêu và tung nhát chém lửa, gây sát thương vật lý (18 + 0.8x ATK) kèm đốt cháy 8 sát thương/lượt trong 2 lượt. Sát thủ bậc thấp + DOT lửa. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='flame_combo_assassin', damageType='physical', base='18', scaleStat='atk', scale='0.8', poisonTurns='2', poisonPerTurn='8'),
    make_row(id='quick_strike_rage', name='Đâm Nhanh',
        descriptionVi="Chồn Nhanh lao nhanh phía sau mục tiêu và đâm nhẹ, gây sát thương vật lý (12 + 0.55x ATK) nhưng hồi +3 nộ cho bản thân. Sát thủ tích nộ nhanh để tung chiêu liên hoàn. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='quick_strike_rage', damageType='physical', base='12', scaleStat='atk', scale='0.55', rageGain='3'),
    make_row(id='web_trap_slow', name='Mạng Tơ Bẫy',
        descriptionVi="Nhện Độc giăng mạng tơ bẫy mục tiêu, gây sát thương vật lý (16 + 0.7x ATK) và giảm ATK mục tiêu 15% trong 2 lượt. Sát thủ bậc thấp kèm debuff. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='web_trap_slow', damageType='physical', base='16', scaleStat='atk', scale='0.7', turns='2'),
    make_row(id='sting_paralyze', name='Đuôi Chích',
        descriptionVi="Bọ Cạp Bóng chích đuôi vào mục tiêu từ phía sau, gây sát thương vật lý (18 + 0.75x ATK) và có 30% tỷ lệ choáng 1 lượt. Sát thủ bậc thấp kèm CC. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='sting_paralyze', damageType='physical', base='18', scaleStat='atk', scale='0.75', stunChance='0.30', stunTurns='1'),
    # T2
    make_row(id='unit_skill_wolf_alpha', name='Tru Hào Sát Thủ',
        descriptionVi="Sói Thủ Lĩnh lao sau lưng mục tiêu và tấn công, gây sát thương vật lý (22 + 0.9x ATK), đồng thời tăng +10 ATK bản thân trong 2 lượt và kích đòn phụ đồng minh cùng hàng (40%). Sát thủ phối hợp bầy. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='self_atk_and_assist', damageType='physical', base='22', scaleStat='atk', scale='0.9', selfAtkBuff='10', assistRate='0.40', turns='2'),
    make_row(id='unit_skill_mosquito_toxic', name='Vòi Hút Máu',
        descriptionVi="Muỗi Độc lao sau lưng mục tiêu và cắm vòi hút máu, gây sát thương vật lý (24 + 0.95x ATK) và hút 40% thành máu. Gây dịch bệnh 8 sát thương/lượt trong 2 lượt. Sát thủ hút máu + DOT. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='lifesteal_disease', damageType='physical', base='24', scaleStat='atk', scale='0.95', lifesteal='0.40', diseaseTurns='2', diseaseDamage='8'),
    make_row(id='stealth_strike', name='Ẩn Đánh',
        descriptionVi="Hươu Cao Cổ Ẩn lao sau lưng mục tiêu và tấn công bất ngờ, gây sát thương vật lý (22 + 0.85x ATK) và tự buff né 20% trong 2 lượt. Sát thủ tấn công an toàn. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='stealth_strike', damageType='physical', base='22', scaleStat='atk', scale='0.85', evadeBuff='0.20', turns='2'),
    make_row(id='double_poison_hit', name='Cắn Độc Kép',
        descriptionVi="Giun Tấn Công lao sau lưng mục tiêu và cắn 2 đòn liên tiếp, mỗi đòn gây sát thương vật lý (12 + 0.5x ATK) kèm độc cộng dồn 8 sát thương/lượt. Sát thủ DOT cộng dồn. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='double_poison_hit', damageType='physical', base='12', scaleStat='atk', scale='0.5', poisonTurns='2', poisonPerTurn='8'),
    # T3
    make_row(id='unit_skill_bat_blood', name='Cắn Mạch Hút Máu',
        descriptionVi="Dơi Huyết lao sau lưng mục tiêu và cắn sâu vào mạch máu, gây sát thương vật lý (28 + 1.1x ATK) và hút 35% sát thương gây ra thành máu. Sát thủ sống dai nhờ hút máu. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='single_burst_lifesteal', damageType='physical', base='28', scaleStat='atk', scale='1.1', lifesteal='0.35'),
    make_row(id='x_slash_bleed', name='Kiếm Chém X',
        descriptionVi="Bọ Ngựa Kiếm chém mạnh hình chữ X vào mục tiêu từ phía sau, gây sát thương vật lý (28 + 1.05x ATK) kèm chảy máu 12 sát thương/lượt trong 3 lượt. Sát thủ DOT chảy máu mạnh. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='x_slash_bleed', damageType='physical', base='28', scaleStat='atk', scale='1.05', turns='3'),
    make_row(id='backstab_crit', name='Cắn Gáy',
        descriptionVi="Chồn Hương Bóng lẻn phía sau mục tiêu và cắn vào gáy, gây sát thương vật lý (30 + 1.15x ATK), x1.5 sát thương nếu đứng phía sau mục tiêu. Sát thủ burst từ sau lưng. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='backstab_crit', damageType='physical', base='30', scaleStat='atk', scale='1.15'),
    make_row(id='silent_kill_stealth', name='Ám Sát Thầm Lặng',
        descriptionVi="Chồn Mink Im lặng lẻn sau lưng mục tiêu và tấn công, gây sát thương vật lý (28 + 1.1x ATK). Nếu hạ gục mục tiêu, tự tăng né 25% trong 2 lượt. Sát thủ ám sát + thoát thân. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='silent_kill_stealth', damageType='physical', base='28', scaleStat='atk', scale='1.1'),
    # T4
    make_row(id='unit_skill_lynx_echo', name='Ảnh Trảm',
        descriptionVi="Châu Chấu Gió lao sau lưng mục tiêu và chém, để lại bóng ảnh gây thêm 1 đòn trễ (18 + 0.8x ATK). Tổng 2 đòn tạo burst bất ngờ. Sát thương chính (32 + 1.3x ATK). Sát thủ combo T4. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='single_delayed_echo', damageType='physical', base='32', scaleStat='atk', scale='1.3', echoBase='18', echoScale='0.8'),
    make_row(id='unit_skill_cobra_venom', name='Nọc Độc Tử Thần',
        descriptionVi="Rắn Hổ Mang phun nọc độc cực mạnh vào mục tiêu, gây sát thương phép (35 + 1.3x MATK) và nhiễm độc 22 sát thương/lượt trong 3 lượt. Sát thủ phép thuật DOT cấp cao. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='single_strong_poison', damageType='magic', base='35', scaleStat='matk', scale='1.3', poisonTurns='3', poisonPerTurn='22'),
    make_row(id='scavenge_heal', name='Xé Xác',
        descriptionVi="Kền Kền Ăn Xác lao sau lưng mục tiêu và xé xác, gây sát thương vật lý (35 + 1.3x ATK). Nếu hạ gục mục tiêu, hồi 30% HP bản thân. Sát thủ kết liễu + tự hồi phục. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='scavenge_heal', damageType='physical', base='35', scaleStat='atk', scale='1.3'),
    make_row(id='unit_skill_wasp_assassin', name='Kiếm Dao Sát Thủ',
        descriptionVi="Dao Ong Sát Thủ chém mạnh vào điểm yếu mục tiêu, gây sát thương vật lý (38 + 1.5x ATK) và bỏ qua 35% giáp. Sát thủ đơn mục tiêu T4 sát thương cao. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='single_burst_armor_pen', damageType='physical', base='38', scaleStat='atk', scale='1.5', armorPen='0.35'),
    # T5
    make_row(id='unit_skill_panther_void', name='Tất Sát Hư Không',
        descriptionVi="Báo Hư Không lao vòng ra sau lưng mục tiêu và giáng đòn chí tử, gây sát thương vật lý (65 + 2.8x ATK). Nếu hạ gục, hoàn lại 50% Nộ tối đa. Sát thủ burst cao nhất game. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='assassin_execute_rage_refund', damageType='physical', base='65', scaleStat='atk', scale='2.8', killRage='0.5'),
    make_row(id='death_mark', name='Tử Thần Gõ Cửa',
        descriptionVi="Linh Hồn Mộ đánh dấu tử thần lên mục tiêu, gây sát thương vật lý (25 + 0.9x ATK) ngay lập tức. Sau 2 lượt, dấu kích hoạt gây true damage = 25% HP đã mất. Sát thủ trì hoãn cực mạnh. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='death_mark', damageType='physical', base='25', scaleStat='atk', scale='0.9', turns='2'),
    make_row(id='unit_skill_wraith_shadow', name='Hỏa Ấn Liên Kích',
        descriptionVi="Ma Bóng Tối lao sau lưng mục tiêu và tung 2 nhát liên tiếp. Nhát đầu gây (32 + 1.4x ATK), nhát hai gây (26 + 1.2x ATK). Tổng 2 đòn tạo burst damage khủng khiếp. Sát thủ combo T5. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='double_hit', damageType='physical', base='32', scaleStat='atk', scale='1.4',
        hit1='{"base":32,"scale":1.4}', hit2='{"base":26,"scale":1.2}'),
    make_row(id='unit_skill_reaper_void', name='Tất Sát Bóng Tối',
        descriptionVi="Tử Thần Hư Không lao vòng ra sau lưng mục tiêu giáng đòn chí tử, gây sát thương vật lý (60 + 2.5x ATK). Ưu tiên tấn công carry yếu giáp ở hậu phương. Sát thương đơn mục tiêu cực cao. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='ASSASSIN_BACK', effect='single_burst', damageType='physical', base='60', scaleStat='atk', scale='2.5'),
]

# ══════════════════════════════════════════════════════════════
# SUPPORT SKILLS (20 units)
# ══════════════════════════════════════════════════════════════

SUPPORT = [
    # T1
    make_row(id='heal_over_time', name='Khúc Ca Sức Sống',
        descriptionVi="Nai Thần Ca hát bài ca sức sống, gắn hiệu ứng hồi máu theo lượt cho 2 đồng minh yếu nhất trong 3 lượt. Mỗi lượt hồi một lượng HP nhỏ. Hỗ trợ bậc thấp hồi máu ổn định. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='heal_over_time', turns='3', maxTargets='2'),
    make_row(id='peace_heal_reduce', name='Cành Ô Liu',
        descriptionVi="Bồ Câu Hòa Bình trao cành ô liu cho đồng minh yếu nhất, hồi (18 + 0.15x MATK) HP và giảm 15% sát thương nhận trong 1 lượt. Hỗ trợ bậc thấp hồi + giảm damage. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='peace_heal_reduce', base='18', scaleStat='matk', scale='0.15'),
    make_row(id='bless_rain_mdef', name='Mưa Phước Lành',
        descriptionVi="Gà Trống Phước ban phước lành cho toàn đội, tăng kháng phép +12 cho toàn bộ đồng minh trong 2 lượt. Hỗ trợ bậc thấp buff kháng phép diện rộng. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='bless_rain_mdef', mdefBuff='12', turns='2'),
    make_row(id='light_purify', name='Ánh Sáng Chữa Lành',
        descriptionVi="Đom Đóm Chữa phát ánh sáng thanh tẩy, xóa 1 debuff ngẫu nhiên của 2 đồng minh và hồi thêm (15 + 0.1x MATK) HP. Hỗ trợ bậc thấp thanh tẩy + hồi. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='light_purify', base='15', scaleStat='matk', scale='0.1', maxTargets='2'),
    # T2
    make_row(id='mirror_reflect', name='Vảy Gương',
        descriptionVi="Bướm Kính tạo khiên gương bảo vệ bản thân (40 HP) và phản 20% sát thương phép nhận được trong 2 lượt. Hỗ trợ chống pháp sư hiệu quả. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='mirror_reflect', shieldBase='40', reflectPct='0.20', turns='2'),
    make_row(id='unicorn_atk_buff', name='Sừng Kỳ Lân',
        descriptionVi="Ngựa Kỳ Sáng phóng tia sáng từ sừng, buff ATK +20% cho đồng minh ATK cao nhất trong 3 lượt. Hỗ trợ tăng sức mạnh cho carry chủ lực. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='unicorn_atk_buff', turns='3'),
    make_row(id='spring_aoe_heal', name='Suối Nguồn',
        descriptionVi="Tiên Rừng triệu hồi suối nguồn chữa lành, hồi (22 + 0.15x MATK) HP cho TẤT CẢ đồng minh. Hỗ trợ hồi máu diện rộng, hiệu quả khi toàn đội bị thương. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='spring_aoe_heal', base='22', scaleStat='matk', scale='0.15'),
    make_row(id='root_snare', name='Rễ Cây Ràng Buộc',
        descriptionVi="Yêu Tinh Cây triệu hồi rễ cây trói chặt 1 kẻ địch, gây sát thương phép nhẹ (12 + 0.35x MATK) kèm im lặng 1 lượt và tự hồi 8% HP. Hỗ trợ CC + tự sustain. Mốc sao: 1★ sát thương gốc, 2★ +20% sát thương, 3★ +40% sát thương.",
        actionPattern='RANGED_STATIC', effect='root_snare', damageType='magic', base='12', scaleStat='matk', scale='0.35'),
    # T3
    make_row(id='mimic_rage_buff', name='Bắt Chước',
        descriptionVi="Vẹt Linh Hô bắt chước tiếng kêu chiến đấu, hồi +2 nộ cho 1 đồng minh nộ thấp nhất. Giúp đồng minh chủ lực nhanh chóng tung chiêu thức. Hỗ trợ tăng tốc nộ hiệu quả. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='mimic_rage_buff', rageGain='2'),
    make_row(id='soul_link_heal', name='Hồn Hộ Mệnh',
        descriptionVi="Hồn Ma Sáng liên kết linh hồn với đồng minh yếu nhất, hồi 100% sát thương Hồn Ma nhận thành HP cho đồng minh trong 2 lượt. Hỗ trợ hồi máu gián tiếp độc đáo. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='soul_link_heal', turns='2'),
    make_row(id='mass_cleanse', name='Dòng Nước Thanh Tẩy',
        descriptionVi="Tiên Nước triệu hồi dòng nước thanh tẩy, xóa TẤT CẢ debuff của 1 đồng minh và hồi 12% HP tối đa. Hỗ trợ thanh tẩy mạnh nhất bậc 3. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='mass_cleanse'),
    make_row(id='wind_shield_ally', name='Gió Hộ Mệnh',
        descriptionVi="Yêu Tinh Gió tạo khiên gió bảo vệ 2 đồng minh yếu nhất, hấp thụ (35 + 0.25x MATK) sát thương. Bảo vệ carry khỏi burst damage. Hỗ trợ khiên T3. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='wind_shield_ally', shieldBase='35', shieldScaleStat='matk', shieldScale='0.25', maxTargets='2'),
    # T4
    make_row(id='unit_skill_qilin_breeze', name='Lối Gió Kỳ Lân',
        descriptionVi="Kỳ Lân Gió tạo luồng gió mạnh, tăng +12 ATK và +12% né tránh cho toàn bộ đồng minh cùng cột trong 2 lượt. Hỗ trợ buff ATK + né cho carry cùng cột. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='column_bless', turns='2', evadeBuff='0.12', atkBuff='12'),
    make_row(id='unit_skill_peacock_dazzle', name='Điệu Múa Mê Hoặc',
        descriptionVi="Khổng Tước Vũ xòe đuôi múa điệu mê hoặc, gây sát thương phép nhỏ (22 + 0.65x MATK) và giảm 25% ATK toàn bộ kẻ địch trong 2 lượt. Khắc chế đội hình sát thương vật lý. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='RANGED_STATIC', effect='global_debuff_atk', damageType='magic', base='22', scaleStat='matk', scale='0.65', turns='2'),
    make_row(id='unit_skill_swan_grace', name='Khiên Thiên Nga',
        descriptionVi="Thiên Nga Trắng tạo lá chắn nước tinh khiết cho đồng minh yếu nhất, hấp thụ (65 + 0.8x MATK) sát thương và xóa 1 debuff. Bảo vệ carry khỏi burst cấp cao. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='shield_cleanse', shieldBase='65', shieldScaleStat='matk', shieldScale='0.8'),
    make_row(id='revive_or_heal', name='Thiên Sứ Tái Sinh',
        descriptionVi="Thiên Thần Hộ Vệ kêu gọi phép màu, 50% hồi sinh 1 đồng minh đã ngã với 25% HP hoặc hồi 15% HP cho toàn đội nếu không có ai chết. Hỗ trợ hồi sinh cấp cao. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='revive_or_heal'),
    # T5
    make_row(id='phoenix_rebirth', name='Lửa Bất Diệt',
        descriptionVi="Phượng Hoàng Lửa thiêu cháy bản thân trong lửa tái sinh, hồi 40% HP cho đồng minh yếu nhất. Khi Phượng Hoàng chết, tự hồi sinh 1 lần với 30% HP. Hỗ trợ hồi sinh bản thân T5. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='phoenix_rebirth'),
    make_row(id='unit_skill_lizard_elder', name='Phúc Lành Cổ Thụ',
        descriptionVi="Rồng Đất Cổ kêu gọi sức mạnh đại địa, tăng +22 Giáp và +22 Kháng Phép cho toàn bộ đồng minh trong 3 lượt. Đồng thời hồi 50 HP cho đồng minh yếu nhất. Hỗ trợ def buff toàn đội T5. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='team_def_buff', armorBuff='22', mdefBuff='22', turns='3'),
    make_row(id='unit_skill_seraphim_light', name='Ánh Sáng Seraphim',
        descriptionVi="Seraphim Ánh Sáng tỏa ánh sáng thần thánh, hồi (40 + 1.3x MATK) HP cho 3 đồng minh yếu nhất. Nếu có đồng minh chết lượt trước, hồi sinh với 25% HP. Hỗ trợ hồi máu + hồi sinh T5. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='dual_heal', base='40', scaleStat='matk', scale='1.3'),
    make_row(id='unit_skill_oracle_wisdom', name='Tiên Tri Trí Tuệ',
        descriptionVi="Tiên Tri Trí Tuệ nhìn thấu tương lai, cộng +2 nộ cho 3 đồng minh gần nhất và tăng +10 ATK toàn đội trong 2 lượt. Tăng tốc nộ + buff ATK toàn diện cấp cao nhất. Mốc sao: 1★ hiệu lực gốc, 2★ +20% hiệu lực, 3★ +40% hiệu lực.",
        actionPattern='SELF', effect='team_rage', rageGain='2', maxTargets='3', atkBuff='10', turns='2'),
]
